version: '3.4'

services:

  test.api:
      container_name: test-api-container
      restart: always
      build:
        context: .
        dockerfile: MvcApp/Dockerfile
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:80
      ports:
        - "5000:80"
      networks:
          - ngnix-network
        
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
        - ngnix-network

networks:
  ngnix-network:
    external: true
